### ISSUE TITLE
One user can endorse a skill multiple times 

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/spekni#85]
![WhatsApp Image 2022-08-02 at 10 42 21 AM](https://user-images.githubusercontent.com/62628408/182346935-91a324f7-4122-492f-9eeb-2aee9bbed14a.jpeg)

This shouldn't be possible, the expected behavior is for one user to be able to endorse a skill only once.

**Comment by SpiffGreen** [comment]
Fixed with https://github.com/Evavic44/spekni/commit/fd3ee3adec8ac3e6562713731757b6632dc1e085
